# ============================================
# output_generator.py
# Generates Excel, JSON, and Text Report outputs
# ============================================

import os
import json
import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from config import OUTPUT_DIR


def _ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def _timestamp():
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def save_json(result: dict, filename: str) -> str:
    _ensure_output_dir()
    output_path = os.path.join(OUTPUT_DIR, f"{filename}_{_timestamp()}.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=4, ensure_ascii=False)
    print(f"  ✅ JSON saved: {output_path}")
    return output_path


def save_text_report(result: dict, filename: str) -> str:
    _ensure_output_dir()
    output_path = os.path.join(OUTPUT_DIR, f"{filename}_{_timestamp()}.txt")
    extracted = result.get("extracted_info", {})

    report = f"""
╔══════════════════════════════════════════════════════════════════╗
║         INTELLIGENT DOCUMENT PROCESSING REPORT                  ║
╚══════════════════════════════════════════════════════════════════╝

📄 FILE NAME     : {result.get('file_name', 'N/A')}
📁 FILE TYPE     : {result.get('file_type', 'N/A')}
🕐 PROCESSED AT  : {result.get('processed_at', 'N/A')}
📦 FILE SIZE     : {result.get('file_size', 'N/A')}
🏷️  CATEGORY      : {result.get('category', 'N/A')}
🎭 TONE          : {result.get('tone', 'N/A')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{result.get('summary', 'N/A')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔍 EXTRACTED KEY INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📅 Dates         : {', '.join(extracted.get('dates', [])) or 'None found'}
👤 Names         : {', '.join(extracted.get('names', [])) or 'None found'}
🔢 Numbers       : {', '.join(extracted.get('numbers', [])) or 'None found'}
📌 Topics        : {', '.join(extracted.get('topics', [])) or 'None found'}
📍 Locations     : {', '.join(extracted.get('location', [])) or 'None found'}
✅ Action Items  :
{chr(10).join(f'  • {item}' for item in extracted.get('action_items', [])) or '  None found'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
              Generated by Intelligent Document Processor
              Powered by Groq (LLaMA) | Jaheer Khan
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"  ✅ Text Report saved: {output_path}")
    return output_path


def save_excel(results: list, filename: str = "summary") -> str:
    _ensure_output_dir()
    output_path = os.path.join(OUTPUT_DIR, f"{filename}_{_timestamp()}.xlsx")

    wb = Workbook()
    ws = wb.active
    ws.title = "Document Summary"

    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    center = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thin_border = Border(
        left=Side(style="thin"), right=Side(style="thin"),
        top=Side(style="thin"), bottom=Side(style="thin")
    )

    headers = [
        "File Name", "File Type", "Category", "Tone",
        "Summary", "Dates", "Names", "Numbers",
        "Topics", "Locations", "Action Items", "Processed At"
    ]

    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_num, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = center
        cell.border = thin_border

    row_fills = ["EBF5FB", "D6EAF8"]

    for row_num, result in enumerate(results, start=2):
        extracted = result.get("extracted_info", {})
        fill_color = PatternFill("solid", fgColor=row_fills[row_num % 2])

        row_data = [
            result.get("file_name", ""),
            result.get("file_type", ""),
            result.get("category", ""),
            result.get("tone", ""),
            result.get("summary", ""),
            ", ".join(extracted.get("dates", [])),
            ", ".join(extracted.get("names", [])),
            ", ".join(extracted.get("numbers", [])),
            ", ".join(extracted.get("topics", [])),
            ", ".join(extracted.get("location", [])),
            "\n".join(extracted.get("action_items", [])),
            result.get("processed_at", ""),
        ]

        for col_num, value in enumerate(row_data, 1):
            cell = ws.cell(row=row_num, column=col_num, value=value)
            cell.fill = fill_color
            cell.alignment = Alignment(wrap_text=True, vertical="top")
            cell.border = thin_border

    col_widths = [25, 12, 25, 20, 50, 20, 25, 20, 30, 20, 35, 22]
    for i, width in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = width

    ws.row_dimensions[1].height = 30
    ws.freeze_panes = "A2"

    wb.save(output_path)
    print(f"  ✅ Excel saved: {output_path}")
    return output_path